language: node_js
node_js:
  - '14'

root:
  dist: xenial
  os: linux

cache:
  directories:
    - 'node_modules'

branches:
  only:
    - master

install:
  - npm install

script:
  - echo "Build app"
  - npm run build

deploy:
  provider: pages
  strategy: git
  repo: PawelKlapec/PawelKlapec.github.io
  token: $GITHUB_ACCESS_TOKEN
  target_branch: master
  local_dir: build
  on:
    branch: master