language: node_js
node_js:
  - '14'

cache:
  directories:
    - 'node_modules'

branches:
  only:
    - master

install:
  - npm install

script:
  - echo "Build app"
  - npm run build

deploy:
  provider: pages
  repo: PawelKlapec/PawelKlapec.github.io
  skip-cleanup: true
  github-token: $GITHUB_ACCESS_TOKEN
  target-branch: master
  local-dir: build
  on:
    branch: master